# Generated by Django 4.2 on 2023-04-26 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_document_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=250)),
                ('date_held', models.DateField()),
                ('duration', models.IntegerField(default=1)),
                ('place_held', models.CharField(max_length=250, null=True)),
                ('documents', models.ManyToManyField(to='database.document')),
                ('eventActivityLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventActivityRoles', to=settings.AUTH_USER_MODEL)),
                ('eventFRLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventFRLeaderRoles', to=settings.AUTH_USER_MODEL)),
                ('eventHRLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventHRLeaderRoles', to=settings.AUTH_USER_MODEL)),
                ('eventManager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventManagerRoles', to=settings.AUTH_USER_MODEL)),
                ('eventMediaLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventMediaLeaderRoles', to=settings.AUTH_USER_MODEL)),
                ('eventOrganisationLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventOrganisationLeaderRoles', to=settings.AUTH_USER_MODEL)),
                ('eventPRLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventPRLeaderRoles', to=settings.AUTH_USER_MODEL)),
                ('eventViceManager', models.ManyToManyField(related_name='eventViceManagerRoles', to=settings.AUTH_USER_MODEL)),
                ('hosts', models.ManyToManyField(null=True, related_name='HostedEvents', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(to='database.image')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
